### ISSUE TITLE
Practica 2, Inducción Matemática

### ISSUE THREAD

**Issue by Fidel20-01** [SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-equipo-de-jp#1]
[Reporte de practica Induccion Matematica Act 3.pdf](https://github.com/user-attachments/files/17529443/Reporte.de.practica.Induccion.Matematica.Act.3.pdf)

**Comment by Fidel20-01** [comment]
[Uploading Reporte de practica Induccion Matematica Act 3.pdf…]()

**Comment by Proyect-A16** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:22/25
Total:98/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
